#!/usr/bin/env python

import rospy
from rosbridge_push import RosbridgePushClient

if __name__ == "__main__":
    rospy.init_node("rosbridge_push", log_level=rospy.DEBUG)

    while not rospy.is_shutdown():
        rospy.loginfo("Hi")
        rospush_client = RosbridgePushClient("ws://jrokisky.com:8080")
        rospush_client.connect()
        rospush_client.send("hello!")
        rospush_client.recv()
        rospush_client.close()
        rospy.sleep(10)

