#!/usr/bin/env python

import rospy
from rosbridge_push import RosbridgePushClient

if __name__ == "__main__":
    rospy.init_node("rosbridge_push", log_level=rospy.DEBUG)
    rospy.loginfo("Starting rosbridge_push")
    rospush_client = RosbridgePushClient("ws://jrokisky.com:8080")
    rospy.on_shutdown(rospush_client.close)

    while not rospy.is_shutdown():
        if not rospush_client.isConnected():
            rospush_client.connect()
            rospy.sleep(10)
        else:
            rospush_client.recv();
            


